version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: stock_app_db
    environment:
      POSTGRES_DB: stock_app
      POSTGRES_USER: adminUser
      POSTGRES_PASSWORD: qwe123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminUser -d stock_app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: